# Generated by Django 4.1.4 on 2022-12-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingresa el nombre del Director ', max_length=64)),
                ('apellido', models.CharField(help_text='Ingresa el apellido del Director', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_movie', models.CharField(help_text='Ingrese el nombre de la pelicula', max_length=100)),
            ],
        ),
    ]
